---
# tasks file for k8s-node
- name: Create directories for local storage
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  loop: "{{ storage_directories }}"

- name: Run k3s install role
  ansible.builtin.include_role:
    name: xanmanning.k3s
  vars:
    k3s_become: true
# - include_tasks: firewall.yml
#   tags:
#     - debug

# - include_tasks: flux-bootstrap.yml
#   tags:
#     - debug
