---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          - age1m2y767l07m8z6hcc5phynkkxn8g0zdqhmvru9racxsncqgmwmp8qxqnvy4
          - age1pute6uutcfa83zfgls9nszmu7e30he6txh89n3wttchu4vx6kq8q9tcy5p
  - path_regex: kubernetes/.*\.sops\.ini
    key_groups:
      - age:
          - age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          - age1m2y767l07m8z6hcc5phynkkxn8g0zdqhmvru9racxsncqgmwmp8qxqnvy4
          - age1pute6uutcfa83zfgls9nszmu7e30he6txh89n3wttchu4vx6kq8q9tcy5p
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
      - age:
          - age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          - age1m2y767l07m8z6hcc5phynkkxn8g0zdqhmvru9racxsncqgmwmp8qxqnvy4
          - age1pute6uutcfa83zfgls9nszmu7e30he6txh89n3wttchu4vx6kq8q9tcy5p
  - path_regex: kubernetes/.*\.sops\.json
    key_groups:
      - age:
          - age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          - age1m2y767l07m8z6hcc5phynkkxn8g0zdqhmvru9racxsncqgmwmp8qxqnvy4
          - age1pute6uutcfa83zfgls9nszmu7e30he6txh89n3wttchu4vx6kq8q9tcy5p
  - path_regex: provision/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          - age1m2y767l07m8z6hcc5phynkkxn8g0zdqhmvru9racxsncqgmwmp8qxqnvy4
          - age1pute6uutcfa83zfgls9nszmu7e30he6txh89n3wttchu4vx6kq8q9tcy5p
