---
version: "3"
vars:
  PROVISION_DIR: "{{.ROOT_DIR}}/provision"
  ANSIBLE_DIR: "{{.PROVISION_DIR}}/kubernetes/servers"
  KUBECONFIG: $KUBECONFIG
  SSH_USERNAME: $SSH_USERNAME

includes:
  pv: .taskfiles/Ansible/Tasks.yml
  flux: .taskfiles/Flux/Tasks.yml
