apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: infra
stringData:
    admin-password: ENC[AES256_GCM,data:bLvMam6fY4DKp+P/C5Bdepu+1L0Q3RdlA7vdoPlC0aZabgUlDHqTq3HagnYN3gFj5LGHcS4oIE7wDuU9dO9m18zaYgdY3zB7,iv:dQLydTcKeFSY9IU3umpb3+43CFDM+aPmgvIQVqMOPis=,tag:C/HEHOJXj6cLLNxjmfSMmQ==,type:str]
    admin-user: ENC[AES256_GCM,data:5GG+VTY=,iv:LUO7+m9DLrkZtVzPolr2InD+9vLGlYXYUJOnFOQ00fg=,tag:YMdwFfVFu0lMW8/UIfgOVw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWWRWNWdSeEEvUDlPMUIx
            aWR6VytKV2FCVDRhYUxhbkZuWjYzRS9SOTNFCk1wTHBJQWo3cGY3NGJEMWVhaCtC
            WFNPeWNpYmxlMjE3dXBEeVJ2RWZkRXMKLS0tIHB2Wm10WXJPa2JlN09Rb2JRTlpr
            VDVNTEVrYUpMVjJSckpTMEF5UXI1MlEKXxY687xMe8zNCppoQap1NyIjeGVkWXlW
            bCNmwRfhY4bbvqX11r5zC62wk04VZQHivk/0IUfh33OlJm870LWaPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m2y767l07m8z6hcc5phynkkxn8g0zdqhmvru9racxsncqgmwmp8qxqnvy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNTN1TnBiUnE1eVZPZkpr
            NnBQV1Z6SmhhTHVtczZsVmJydXZxQW5LRjNVCm5LUzh5OUlMaVU4ZU1wQmxKMHo5
            Yi9hVHowMkxCQ0tjc1ZpOGIzREtPYzgKLS0tIHFmUGY3UGJuVXAzWjBVZVlwazZQ
            STBzQzF0blhBR0xMRTNnR2tUQ1dnczAKmc4oKR9qSuL/CIsshFQBjIol3LO8uKQh
            c1NiKrWDhmJ9QXblf4p+FkafPX6YTvIrvvZFpJRzxSHknfsA5wcA9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gxxh834vfwthpypxc04hqzcavwk46t2d3nj896hjgexq05zq6gzsmh9mfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZVVodkt2ZU1wVTF6UlB2
            dlhoSEpJcFNrN2czdFJ6bWNLLzR4Smk4ZW1rCjVGQ1pXZFBLd1c2UmdGbjdNTEtY
            Zno1dEh3ZzFxcTlGNjZZd1BLeVJzKzgKLS0tIEx4SG41RTBzQzljUjhTQWV6Y2k3
            ZDlDQ2h3Nlc5Sll3dFRibWpRYkszS2sKy6JoCTF3D9MkRskgLf8EO7XAPoe5inKu
            DyX078CsVplYSyNJs+HNF+MRuuvHZXu/6hnFTTsZY80c+QfLw2c7OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T10:59:48Z"
    mac: ENC[AES256_GCM,data:a438vbpOOVOPGRvjq2VmIQbEed4H8Szg5QOEHgzDkQXjoYSmtbauJp3WbQq0ajcKgm81d/2Hlu0JNaTQdhe/MARCZTAx9zG+tOqd1FNN5T5nYKM7uj/3dTZ8fww+I9MjKiGArK2ljxP9JcsPBN27GmO19dLa36jAm3+8P7JZgW0=,iv:yDJq5ihADgOjK9D4Vb+gWNs1fRgUaU4mN/Gz1zyMkyM=,tag:mBClFtwKaRuHOf+k62ffgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
