---
version: "3"

tasks:
  deps:
    desc: Install/update ansible dependencies
    dir: "{{.ANSIBLE_DIR}}"
    cmd:
      - ansible-galaxy install -r requirements.yml --roles-path $HOME/.ansible/roles --force
      - ansible-galaxy collection install -r requirements.yml --collections-path ~/.ansible/collections --force
    preconditions:
      - test -f "{{.ANSIBLE_DIR}}/requirements.yml"
