---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lldap
  namespace: infra
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8@sha256:0141cf427c47f2d534711a3f9e8c5f9008bc6b585463ccd9288cf0f027e20deb
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: lldap-secret
                key: INIT_POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: lldap-secret
                key: INIT_POSTGRES_DBNAME
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgresql-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: lldap-secret
                key: INIT_POSTGRESQL_USER
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: lldap-secret
                key: LLDAP_LDAP_USER_PASS
