apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:2oe9cdkHoe5TUkQK2fjudmIM3SMMdtLK8bb2nV7UB5uOugLJC8ZmO5Jf4RR+IgaOMI0EH9bT0mqhiYbI,iv:tztbGlLRpDseWe7+pW9eC84w1L/DxamZAavj6UHqtvI=,tag:XzvoTP7hEMxfAFFS1AosZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRURKVlJJUHdDYThIZzRa
            dDRWdEo5VzJHaHB4a3VyclFBNGxKTUJHb3hNCkRHUmJINHJ0cEtydHYyaGJMSjRy
            N0J5Vmx3Q1JacVgwYkVGcUFsbHhFNFEKLS0tIGVFemlRM1N6UEtxbmJzZisxNmFN
            OWhVZHFPWUZUL2pyaWYvcnFTQTEza3MKLung6ldQhJz/ifSa0MDEjsNeJqCVaQ2S
            5/koBnGAPbsQ8YSZXPNk789IL4C9ZxrhhdbKcGZkjW9t9mZmbHYRBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-21T07:06:42Z"
    mac: ENC[AES256_GCM,data:VW4LUe/6bk/KuJSpVE/lKNDlaf+BPE2vi4Rv6APPGQhfVy+z+qxgOzGOnTRateUZpsCDTr8QdABxuv+qzsm4MFCAFpnOwN5AYJyZsPW/+e6FUJKqAihICzYCr3QmKCLkqxp2ngfc2S++4H2s1dQ60jSv+V6Tnarh2gyvntRgmzQ=,iv:CXSnVeOQWVOF9E7gAnumVeBkXNfzsNCo0CuJHXIc7yA=,tag:h+9Gn+p39+K4TrK+00vtPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
