apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:4PN0J/WzooSgGbZcKo55aSZ5viRsfaNnKVL47OFzeFjCO0SB7I/8kHxz8VibeBeFdwYtlFhIKKc0z3LE,iv:PhA5crswHocUaivGJyztgcEP2PMYDis8w3kWVKxcYuA=,tag:rXc/i75N/OZ3qMyV3Gq/lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL3ROd00raDliYXJSRjAv
            MEF6YlF4aDZwckZ6Y2pQY0VtQml4TTZYZEEwCnVVUHJxbGtNOGE0RmpUTU5VNXBP
            Z1BmQmpLWk84cklPeHBBTTZYWXArancKLS0tIFlNK3dvZTUyUDNEL3Qrc09WRFk1
            bjVIeFJuYjZURG9rR0d3UFdSRWZDdGcKKYWl8es3CaHKSupVlvwKFWgJJz0aSYR+
            VNuCN/RvEXkkZx0etv51uZbACsqmm2Cm2CqtRHETccMi4HyXnbY5GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m2y767l07m8z6hcc5phynkkxn8g0zdqhmvru9racxsncqgmwmp8qxqnvy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT29pNDI0WTMxTVNEeU56
            VDBFRW1jVUdPaE9TZjgvMnA3VndpL0F3Y0FNCjd0MC92UTM5clN6Y3ZwY2pTMHZ1
            MUN1aTVlRm1CWGxYVU13a0lPK3FRdUUKLS0tIDZWOFMvSmdVcENLbWFCSm5SVWpN
            UkFlWTQvOWNReTZ6Tm10Vjc1QytpOHcKcQjklvLP+2/HV7wdmAfq4eXikZgPovrd
            GX7vJbx4cuPIlBwxs2+5LEe0Jlp9dC8fh8wUDmQs1GjTbGY6XedXng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gxxh834vfwthpypxc04hqzcavwk46t2d3nj896hjgexq05zq6gzsmh9mfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U3ZFZ3E3YUs5Z0NubUhD
            NGVITUJ1TVZqc2lZbDg3UFJaUnpKenYrRnpjCllIeEVod0JFSDdSQ1UwUDZWSXBy
            Z0VBbndId1huVzE4VC9rOGRXUzVLbU0KLS0tIDF6T015ZC9qZHdJay9naUt6WE16
            ZEhveG01VHduUmRwSWtEbDNPLzgxdzQKCRnVkrzM9VP7E1db5eP/qd9zgrOEbXlG
            8IR+lnL/0LfDAIWX5xj8SnglF4ZwWfsU7+u2vzlqJIOmHy1KWuHQwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-21T07:32:34Z"
    mac: ENC[AES256_GCM,data:GWzUXsHxngaCdq8SaKhX7VsG6FcEmKO9Kz4/sWtbsSxXQq5wHN8CZn/7B4hFxreytNBY4euHSscWe/HZ2lGtbaiSYCe4NVER/2O8TDQ7H+XutC8Me2je/KaP7O9xy8ph+zNqRFwxMJA4WfS3B3bbB7MTHK2fxJBPpdmCW6bF6Us=,iv:Hfw8rbKFrg4Wpm6sK5S2HWiB+3aBs1CCaxhKiB5LYyQ=,tag:gq79uYNLKt+GFstNtMLt4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
