# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    GITHUB_REPO_URL: ENC[AES256_GCM,data:cf4S0HNkdnwWwkJ5Dffgd4/zh1v4l8ZX4QGgPz/BMkkSzaaA557Jbm4=,iv:vonruUusa7vZGJyiBgNC8zb0f2L3FUCc+j3ymMe3H0k=,tag:yK6YON7/Y5cX1UTSDOs68Q==,type:str]
    ROOT_DOMAIN: ENC[AES256_GCM,data:p2togDdoeMB5+oHlVCKd,iv:nc/EkpKB/3WwSGZ56/td1KHlDqv2ndbmusqzYwHzXQg=,tag:moOyOyFB6wY+poVMxTgDZA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:dVccbeSuEX5tj1abtEs=,iv:GFIQ45Apg0mSH/emWRW6MwF0wOmSyS6lwO4JUF5g8po=,tag:KeYJyjmbAaxHqa7t3BWJ2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zynf8jeml4f78k4xr7dg7cpgv0et0ctdwxxkn0878e5puvevyceqk3rvkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd0QxQk8vKzZiUk1TaVJp
            bzhsMC9UbHYrSWJvcE0xZXkwZzZKS1ZGSTJRCkJJd0dCRXhzWm10bmFFYzJoRVZ3
            UVRNRFEvMWhLY0QvdG5udm9jQ0hTeGsKLS0tIHd5d2NZRTRKMVVWTFQyNGlKUDhU
            bmt3OUZzYzFWSVN3SHMvdzAzVjlJUDAK7tINKdq4i5cNr638xYPzcsulwt3tO1uG
            3paSVW4MikKKyIcE/cOcmSEeT+eZmvo5dv4uDdgc7Nt7cdBUGK9R4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m2y767l07m8z6hcc5phynkkxn8g0zdqhmvru9racxsncqgmwmp8qxqnvy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTW41S2FrZnBzRXBxWEFw
            YU5hTHJwbEpUU2VXeEJPaVhwSmhQbWlueDFjCllERWZpaVI4ZFUyNEFCSFYrOFVP
            R2UxdSt5RDZ4SGpVNjE5czMzejZYVnMKLS0tIC9DWWhZckpnRm5GR1NQTTlZRTVQ
            ZEhQNld2Q3FaS3VpMFRoMVovS1VUcXMKMbLz6VCV21AV2ieHwOPtbFbvzsK7pwGS
            jvLZ3wIhVRTHb1bXlbEPy8jaHmusMhAfseJ1BzY4pw0s3kDNQjUt3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gxxh834vfwthpypxc04hqzcavwk46t2d3nj896hjgexq05zq6gzsmh9mfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTEFiYVZMQm5wbU4xRWZI
            VElMNGwxeTdkN2FZNnBobUh0UGdjYWVxRlFNCmU1ZGtrWUc4OEl2a3dQNFBOcGZZ
            L3hlSE1KV0FxajJyWFRpYjFXL214V1EKLS0tIDV2RjFRUFIxeGY5bXUrenRYUzZk
            MDUyOWcrV2RhVTRHalU4d1IxZFlTd3cKlgAPHVivTGnkoxQ7qc/GKbD1DeA0ddZ9
            PHTavB28zAILtwg91l6jMP2h21wEDwcGPSUkX98cwPfhWG4Wx+rWJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T13:39:21Z"
    mac: ENC[AES256_GCM,data:dEShfXPEG0zBqzOxLIrxUxmpjoR20GjNySCtF022lwtTVzT5R7cQ0J4qHXh0kM27FNAskLbbV8i1ji7Ou9Za1xZqTPQkunD5VsnEJ2u6Iyz4E9APOQ3McHg7DibRVJYnlS/PwhjJlW3MUoekcg/63wuC3kPM+zL7D1KWqM3+VD4=,iv:cpKLwdnwe0wlvRV8GYujWEb6cCgk0GonomJDygOh0d0=,tag:jtGV8oWWKtcNCLS3gYOoWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
